name: Print Secret Variable - UserX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret
        env:
          MY_VAL: ${{ secrets.PASSWORD }}
        run: |
          import os
          print(os.getenv("MY_VAL"))
        shell: python
